# Generated by Django 5.0.7 on 2024-07-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('formacao', models.TextField()),
                ('hist_prof', models.TextField()),
                ('foco', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('data_envio', models.DateTimeField()),
            ],
        ),
    ]
