# Generated by Django 5.0.7 on 2024-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
